### PR TITLE
Add API endpoint to fetch the index page of the application[Finishes …

### PR DESCRIPTION
**Pull request by Irenyak1**
### What does this PR do?
It creates the API endpoint to return the index page of the application. 
### Tasks completed
- create the route
- write the method

 
@dxania @bekeplar @wasibani-roy

### CODE REVIEW

**Comment by wasibani-roy** [comment]
Hello i wanted to ask why you have index page method in the models.py??
And its purpose there

**Comment by bekeplar** [comment]
I think you have to write your index method in the views.think about it

**Comment by dxania** [comment]
I am asking the same as @wasibani-roy . What is the purpose of the index method in the models?

**Review by Ivankivu — COMMENTED** [review]
this is good progress. Though you might want to make more use of OOP. as it is a very big requirement

**Pull request merged**
